name: publish

on:
  workflow_dispatch: # for now, we will trigger this manually until a bigger maturity is reached
  # release:
  #   types: [released]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - run: npm install
      - run: npm run build
      - uses: JS-DevTools/npm-publish@v3
        with:
          access: public
          token: ${{ secrets.NPMJS_GRANULAR_ACCESS_TOKEN }}
